#!/bin/bash
num=183
while [ $num -gt 103 ]
do
    for pol in `kubectl get cpol | awk '{print $1}'`                                                         
    do
    kubectl get cpol $pol -o yaml | sed -e "s/name: $pol/name: ${pol}-${num}/"
    echo "---"; done >> g2000/allpolicies2000.yaml
    ((num--))
done