#!/bin/bash
num=103
while [ $num -gt 91 ]
do
    for pol in `kubectl get cpol | awk '{print $1}'`                                                         
    do
    kubectl get cpol $pol -o yaml | sed -e "s/name: $pol/name: ${pol}-${num}/"
    echo "---"; done >> g312/allpolicies312.yaml
    ((num--))
done