#!/bin/bash
num=41
while [ $num -gt 20 ]
do
    for pol in `kubectl get cpol | awk '{print $1}'`                                                         
    do
    kubectl get cpol $pol -o yaml | sed -e "s/name: $pol/name: ${pol}-${num}/"
    echo "---"; done >> allpolicies104.yaml
    ((num--))
done